GoalDiggersPrescription/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('main.urls')),
]

accounts/urls.py
from . import views
from django.urls import path, include

app_name = 'accounts'

# Create your views here.
urlpatterns = [
    path('create_user/', views.create_user, name='create_user'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

main/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.home, name='home'),
    path('search_user/', views.search_user, name='search_user'),
    path('user/edit/<user_id>/', views.edit_user, name='edit_user'),
    path('user/delete/<user_id>/', views.delete_user, name='delete_user'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
				<!-- Custom styles -->
				<style>
					.icon-button {
							line-height: 50%;
					}
				</style>
        <title>Goal Digger's Prescription App</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Prescription App</a>
                {% block home_button %}

                {% endblock %}
                {% block logout_button %}

                {% endblock %}
            </div>
        </nav>
        {% block content %}

        {% endblock %}
				<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
				<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
				<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block home_button %}
{#    <form action="{% url 'admin_home' %}" method="GET">#}
{#        <h1>{{ user.user_id }}</h1>#}
{#        <button type="submit" class="btn btn-primary">Home</button>#}
{#    </form>#}
{% endblock %}
{% block logout_button %}
    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-dark">Logout</button>
    </form>
{% endblock %}

templates/non_home.html
{% extends 'base.html' %}

{% block home_button %}
    <form action="{% url 'home' %}" method="GET">
        <button type="submit" class="btn btn-primary">Home</button>
    </form>
{% endblock %}
{% block logout_button %}
    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-dark">Logout</button>
    </form>
{% endblock %}